services:
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - GENERIC_TIMEZONE=Asia/Kolkata
      - NODE_FUNCTION_ALLOW_EXTERNAL=*
    volumes:
      - ./.n8n:/home/node/.n8n
      - ./:/repo